name: Mon Workflow

on: [push]

jobs:
  execute_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v2
      - name: Configuration de Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Exécution du script Python
        run: python demo.py
